// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcGZx4rGMarqZoXMoi8W5oy_jlJ1Fh46k',
    appId: '1:1095246823527:web:a229276e6811da3db554c2',
    messagingSenderId: '1095246823527',
    projectId: 'tickytok-f21f2',
    authDomain: 'tickytok-f21f2.firebaseapp.com',
    storageBucket: 'tickytok-f21f2.appspot.com',
    measurementId: 'G-6KMNSXHCCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrKzv3InlPOlc2AWTDTgkxlmMjkcArhT0',
    appId: '1:1095246823527:android:c55c4b5ccf71ba62b554c2',
    messagingSenderId: '1095246823527',
    projectId: 'tickytok-f21f2',
    storageBucket: 'tickytok-f21f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYhX_L6gc81_bixJAocxzVEcellyiG3I',
    appId: '1:1095246823527:ios:170e88575b7eb0b8b554c2',
    messagingSenderId: '1095246823527',
    projectId: 'tickytok-f21f2',
    storageBucket: 'tickytok-f21f2.appspot.com',
    iosClientId: '1095246823527-vfl1v46a8s0ii6pencjg5vpac9t12g24.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikytokky',
  );
}
